#!/usr/bin/env bash
# Redirection

# update package list
sudo apt update

# install nginx
sudo apt install -y nginx

# Create HTML page
echo "Hello, World!" | sudo tee /var/www/html/index.html

# Define the redirection configuration
redir_config="location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n}"

# Add the redirection configuration to the Nginx default site configuration
sudo sed -i "/server_name _;/a $redir_config" /etc/nginx/sites-enabled/default

# Create HTML page for custom 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/not_found.html

# Define the custom 404 configuration
not_found_config="error_page 404 /not_found.html;\nlocation = /not_found.html {\n\troot /var/www/html;\n\tinternal;\n}"

# Add the custom 404 configuration to the Nginx default site configuration
sudo sed -i "/server_name _;/a $not_found_config" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
