#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

# Update the system and install Nginx
sudo apt update
sudo apt install -y nginx

# Add the custom header to the Nginx configuration
sudo sed -i '/location \/ {/a \        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo systemctl restart nginx
