#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

# Update the system and install Nginx
sudo apt update
sudo apt install -y nginx

# Create HTML page
echo "Hello, World!" | sudo tee /var/www/html/index.html

# Define the redirection configuration
redir_config="location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n}"

# Add the redirection configuration to the Nginx default site configuration
sudo sed -i "/server_name _;/a $redir_config" /etc/nginx/sites-enabled/default

# Create HTML page for custom 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/not_found.html

# Define the custom 404 configuration
not_found_config="error_page 404 /not_found.html;\nlocation = /not_found.html {\n\troot /var/www/html;\n\tinternal;\n}"

# Add the custom 404 configuration to the Nginx default site configuration
sudo sed -i "/server_name _;/a $not_found_config" /etc/nginx/sites-enabled/default

# Add the custom header to the Nginx configuration
sudo sed -i '/location \/ {/a \        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo systemctl restart nginx
