#!/usr/bin/env bash

sudo apt-get -y update
apt-get -y install haproxy

config_server=\
"
frontend web-frontend
        bind *:80
        mode http
        default_backend app

backend app
        balance roundrobin
        server 187158-web-01 100.26.222.78:80 check
        server 187158-web-02 54.197.75.39:80 check
"

echo "$config_server" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
